<?php

namespace Nosco\Ryft\Dtos\Accounts;

use Illuminate\Support\Collection;
use Nosco\Ryft\Dto;
use Nosco\Ryft\Enums\Accounts\AccountDocumentCategory;
use Nosco\Ryft\Enums\Accounts\AccountDocumentType;
use Nosco\Ryft\Support\Helpers;

readonly class RequiredDocument extends Dto
{
    /**
     * @param Collection<AccountDocumentType>|null $accountDocumentTypes
     */
    public function __construct(
        public ?AccountDocumentCategory $category = null,
        public ?Collection $accountDocumentTypes = null,
        public ?int $quantity = null,
    ) {}

    public static function fromArray(array|Collection|null $data): ?static
    {
        if (!$data = Helpers::wrap($data)) {
            return null;
        }

        $data->merge([
            'accountDocumentTypes' => AccountDocumentType::tryFromArray($data->get('accountDocumentTypes', []))
                ->filter(),
        ]);

        return parent::fromArray($data); // TODO: Change the autogenerated stub
    }
}
